kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  lego.email: "lukeaddison785@gmail.com"
  # configre letsencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"