---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: session-db-pvc
  namespace: sock-shop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard