---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-end
data:
  socks.lukeaddison.co.uk.conf: |
    upstream front-end {
      server localhost:8079;
    }

    server {
      listen 80;
      server_name socks.lukeaddison.co.uk;
      root /var/www/html;

      # Proxy the health check to the upstream server at /
      location /healthz {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_next_upstream error;
        proxy_pass http://front-end/;
        break;
      }

      # Proxy everything else to the upstream server, enforcing HTTPS
      location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_next_upstream error;

        # Any request that did not originally come in over HTTPS gets redirected
        if ($http_x_forwarded_proto != "https") {
          rewrite ^(.*)$ https://$server_name$1 permanent;
        }

        proxy_pass http://front-end;

        # Add HTTP Strict Transport Security for good measure.
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains;";
      }
    }

